### PR TITLE
move err msg strings to frozen constants

### PR DESCRIPTION
**Pull request by iirving**
moving Error message string into constant string that are frozen.

at minimum you should freeze strings in place 

Since there isn't any reuse making a constant is low value, but giving them a constant name is the beginning of giving them a key for a external file for i13n values

### CODE REVIEW

**Comment by smiller** [comment]
Hmm.  I would probably do this with 

```
# frozen_string_literal: true
```

at the top of the file instead of multiple `.freeze` calls.

https://docs.ruby-lang.org/en/3.2/syntax/comments_rdoc.html#label-frozen_string_literal+Directive

**Comment by smiller** [comment]
Also, looking for and not finding the test run results, this shows that the github action file should be updated from

```
on: [push]
```

to

```
on: [push, pull_request]
```

**Comment by smiller** [comment]
Also I think these constant names make more sense to me:

```
ERR_INPUT_REQ =>  ERROR_INPUT_OPTION_MISSING
ERR_OUTPUT_REQ => ERROR_OUTPUT_OPTION_MISSING
ERR_INPUT_MISSING => ERROR_INPUT_FILE_NOT_FOUND
ERR_OUTPUT_MISSING => ERROR_OUTPUT_FILE_FOUND 
```

**Comment by iirving** [comment]
- as there are no other strings in file # frozen_string_literal: true makes sense.  I'm more used to individually freezing strings.  👍  
- I'll update inline your more complete and explicit (aka wordy aka meaningful) constant names. 👍 
- I'll revise the PR and we can test github action.  You're welcome! :)

**Comment by iirving** [comment]
@smiller changes made, action is requiring your approval before running 🤞 

bow down before my power (🔋 ) and abuse ( 😈 ) of emjoi's! 
🙈 🙉 🙊 !!

**Comment by smiller** [comment]
Hmm.  The approved action ran and failed.  Not for cause – from the run-tests step, the tests passed and the coverage was maintained, but the SimpleCov Report step failed with the complaint `Error: Resource not accessible by integration`, though the RSpec Report and the Upload coverage results steps were able to access the files they needed.  I re-ran in case it was an intermittent failure and it failed the same way.

Possibly there are different permissions for the GITHUB_TOKEN used in the pull request case?  I'll keep digging, and the github action file might need to change again accordingly.  I'd like this to run green before I pull it in, but there are no further changes required to the code.  Just possibly the action.

This has been a useful exercise, thank you!

**Comment by smiller** [comment]
Hmm.  Went into settings and temporarily gave github actions default “read and write permissions” instead of the basic default of “Read repository contents and packages permissions” and re-ran and it's still failing.   (Which, it shouldn't need to write to access the coverage file and generate a report from it, so, that's probably reasonable.)

**Comment by smiller** [comment]
And a push to a local branch with the same changes as the PR passes with no problem – https://github.com/smiller/format-dual-language/actions/runs/6339261819 – so it's definitely something to do with the PR case.

**Comment by smiller** [comment]
But the same push to a local branch turned into a PR fails in the same place on SimpleCov Report: https://github.com/smiller/format-dual-language/actions/runs/6339437587/job/17218559180

**Review by smiller — APPROVED** [review]

**Pull request merged**
